USE [HRMS_DB]
GO

/****** Object:  Table [dbo].[tblshifts]    Script Date: 05/04/2026 12:19:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblshifts](
	[SHIFTID] [char](2) NOT NULL,
	[SHIFTNAME] [varchar](25) NULL,
 CONSTRAINT [PK_tblshifts] PRIMARY KEY CLUSTERED 
(
	[SHIFTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


